force-app/main/default/objects/Address_Book__c/Address_Book__c.object-meta.xml
<CustomObject>
    <label>Address Book</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses Book</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Book__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Address of the Attendee</description>
    <inlineHelpText>Provide Address of the Attendee</inlineHelpText>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object contains information about the event.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>ticket{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Location of the Event</description>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Events-Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events-Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AttendeeRegistartionPageController.cls
/**
 * @description       : This is a controller class for the Attendee Registartion page
 * @author            : Harshit@mirketa.com
 * @last modified on  : 04-04-2023
 * @last modified by  : Harshit@mirketa.com
**/
public with sharing class AttendeeRegistartionPageController {

    // Properties for Event Attendee, Attendee, Location and a public eventId to store if is passed through URL
    public Event_Attendee__c eveAttendee{get; set;}
    public Attendee__c attendee {get; set;}
    public Address_Book__c locAttendee {get; set;}
    public Id eventId;


    public AttendeeRegistartionPageController() {
    
        //Get the id from the Apex Page.
        eventId = ApexPages.currentPage().getParameters().get('id');
    
        eveAttendee = new Event_Attendee__c();
        attendee = new Attendee__c();
        locAttendee = new Address_Book__c();
        
        //If id was passed the assign it to the event variable
        if(eventId != null){
            eveAttendee.Event__c = eventId;
        }
    }

    // The saveRecord() method inserts the location records, assigns their IDs to the event and organizer, and inserts them as well
    public void saveRecord(){

        //Creating a checkpoint before inserting
        Savepoint sp = Database.setSavepoint();

        try{
        
            insert locAttendee;
            
            //Assigning location in Attendee object
            attendee.Location__c = locAttendee.Id;
            insert attendee;
    
            //Assigning Attendee in Event Attendee object
            eveAttendee.Attendee__c = Attendee.Id;
            insert eveAttendee;
    
            eveAttendee = new Event_Attendee__c();
            attendee = new Attendee__c();
            locAttendee = new Address_Book__c();

        }
        catch(Exception e){
            // If an exception occurs, the method logs the error and rolls back the transaction using a savepoint
            ErrorLogger.logError(e.getMessage(),'Error inserting through Visualforce');
            Database.RollBack(sp);
        }
    
    }
}