force-app/main/default/objects/Address_Book__c/Address_Book__c.object-meta.xml
<CustomObject>
    <label>Address Book</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses Book</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Book__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field contains Email of the Event</description>
    <inlineHelpText>Provide Email of the Event</inlineHelpText>
    <label>Email</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Address of the Attendee</description>
    <inlineHelpText>Provide Address of the Attendee</inlineHelpText>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object contains information about the event.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>ticket{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field contains End Date of the Event</description>
    <inlineHelpText>Provide End Date of the Event</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Location of the Event</description>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>This field contains Max Seats  in the Event</description>
    <inlineHelpText>Provide Max Seats in the Event</inlineHelpText>
    <label>Max Seats</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Starting_Date__c.field-meta.xml
<CustomField>
    <fullName>Starting_Date__c</fullName>
    <description>This field contains Starting Date of Event</description>
    <inlineHelpText>Fill Starting Date of Event</inlineHelpText>
    <label>Starting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Events-Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events-Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTriggerHandlerTest.cls
/**
 * @description       : Test class for EventAttendeeTriggerHandler
 * @author            : Harshit@mirketa.com
 * @last modified on  : 03-23-2023
 * @last modified by  : Harshit@mirketa.com
**/
@isTest
public class EventAttendeeTriggerHandlerTest {
    
    @isTest
    Public static void eventAttendeeTriggerEmailSend(){

        //Create Location record
        Address_Book__c location = new Address_Book__c();
        location.Name = 'Test Location';
        insert location;

        //Create Event record
        Event__c event = new Event__c();
        event.Starting_Date__c = Date.today();
        event.End_Date__c = Date.today().addDays(60);
        event.Location__c = location.id;
        event.Live__c = true;
        event.Max_Seats__c = 100;
        insert event;

        // Create an attendee record
        Attendee__c attendee = new Attendee__c();
        attendee.Name = 'Test Attendee';
        attendee.Email__c = 'testattendee@example.com';
        insert attendee;

        // Create an event attendee record
        Event_Attendee__c eventAttendee = new Event_Attendee__c();
        eventAttendee.Event__c = event.Id;
        eventAttendee.Attendee__c = attendee.Id;

        //Creating List to pass in the method of class EventAttendeeTriggerHandler
        List<Event_Attendee__c> eventAttendeeList = new List<Event_Attendee__c>();
        eventAttendeeList.add(eventAttendee);

        //call the static method to test it
        Test.startTest();
        EventAttendeeTriggerHandler.AttendeeEmailSend(eventAttendeeList);
        Test.stopTest();

         // Verify that the email was sent
         List<EmailMessage> sentEmails = [SELECT Id, ToAddress, subject,TextBody FROM EmailMessage];

         System.assertEquals(1, sentEmails.size());
         System.assertEquals('testattendee@example.com', sentEmails[0].ToAddress);
         System.assertEquals('Pass for the "null"', sentEmails[0].subject);
    }


}