force-app/main/default/objects/Address_Book__c/Address_Book__c.object-meta.xml
<CustomObject>
    <label>Address Book</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses Book</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Book__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object contains information about the event.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>ticket{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Lookup relation for Event Organizer of the Event</description>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>This field contains mode of Event</description>
    <inlineHelpText>Choose the correct mode of event.</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Location of the Event</description>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>This Object include records about Organizers</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address Book</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Events Organizers</relationshipLabel>
    <relationshipName>Events_Organizers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventRegistrationController.cls
/**
 * @description       : This is a controller class for the Event registration page
 * @author            : Harshit@mirketa.com 
 * @last modified on  : 04-04-2023
 * @last modified by  : Harshit@mirketa.com
**/
public with sharing class EventRegistrationController {

    // Properties for Event Organizer, Event, Location
    public  Event_Organizer__c eventOrg {get; set;}
    public Event__c eve {get; set;}
    public Address_Book__c locEvent {get; set;}
    public Address_Book__c locOrganiser {get; set;}

    // Constructor initializes the properties to new instances of their respective sObjects
    public EventRegistrationController() {

        eventOrg = new Event_Organizer__c();
        eve = new Event__c();
        locEvent = new Address_Book__c();
        locOrganiser = new Address_Book__c();

    }

    // The saveRecord() method inserts the location records, assigns their IDs to the event and organizer, and inserts them as well
    public void saveRecord(){

        //Creating a checkpoint before inserting
        Savepoint sp = Database.setSavepoint();

        try{
            
            List<Address_Book__c> location = new List<Address_Book__c>();
            location.add(locOrganiser);   
    
            //Will not add the location of the event type is virtual
            if(eve.Event_Type__c != 'Virtual'){
                location.add(locEvent);        
            }
            
            insert location;
            
            //Assigning Event organiser location in Event organiser object
            eventOrg.Address_Book__c = locOrganiser.id;
                
            insert eventOrg;
            
            //Assigning Event organiser and location in event object
            eve.Location__c = locEvent.id;
            eve.Event_Organizer__C = eventOrg.id;
            insert eve;
            
            
            eve = new Event__c();
            eventOrg = new  Event_Organizer__c();
            locEvent = new Address_Book__c();
            locOrganiser = new Address_Book__c();
        }
        catch(Exception e){

            // If an exception occurs, the method logs the error and rolls back the transaction using a savepoint
            ErrorLogger.logError(e.getMessage(),'Error inserting through Visualforce');            
            Database.RollBack(sp);
        }
    }
}