force-app/main/default/objects/Address_Book__c/Address_Book__c.object-meta.xml
<CustomObject>
    <label>Address Book</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Location Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses Book</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Address_Book__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field contains Email of the Event</description>
    <inlineHelpText>Provide Email of the Event</inlineHelpText>
    <label>Email</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Address of the Attendee</description>
    <inlineHelpText>Provide Address of the Attendee</inlineHelpText>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object contains information about the event.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>ticket{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Lookup relation for Event Organizer of the Event</description>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Location of the Event</description>
    <label>Location</label>
    <referenceTo>Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains Name of Event</description>
    <inlineHelpText>Provide Name of Event</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Starting_Date__c.field-meta.xml
<CustomField>
    <fullName>Starting_Date__c</fullName>
    <description>This field contains Starting Date of Event</description>
    <inlineHelpText>Fill Starting Date of Event</inlineHelpText>
    <label>Starting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Events-Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events-Attendees</relationshipLabel>
    <relationshipName>Events_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>This Object include records about Organizers</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Contains Email of Event Organizer</description>
    <inlineHelpText>Provide Email of Event Organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTriggerHandler.cls
/**
 * @description       : This class is responsible for sending emails to attendees when they register for an event.
 * @author            : Harshit@mirketa.com
 * @last modified on  : 03-23-2023
 * @last modified by  : Harshit@mirketa.com
**/

public class EventAttendeeTriggerHandler {

    //Method used in trigger @param eventAttendeeNewRecords - "trigger.new"
    public static void attendeeEmailSend(List<Event_Attendee__c> eventAttendeeNewRecords) {
        
        // Create an empty list of emails to send
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
       
        // Create sets to hold the event and attendee ids of @param eventAttendeeNewRecords
        Set<Id> eventIds = new Set<Id>();
        Set<Id> attendeeIds = new Set<Id>();

        // Loop through each new event attendee record and add the event and attendee ids to their respective sets
        for (Event_Attendee__c eventAttendeeNewRecord : eventAttendeeNewRecords) {
                eventIds.add(eventAttendeeNewRecord.Event__c);
                attendeeIds.add(eventAttendeeNewRecord.Attendee__c);
        }
        
        // Create a map of events using the event ids obtained earlier
        Map<Id, Event__c> eventMap = new Map<Id, Event__c>([
            SELECT Name__c, Starting_Date__c, Location__r.Name, Event_Organizer__r.Name 
            FROM Event__c 
            WHERE Id IN :eventIds
        ]);
        
        // Create a map of attendees using the attendee ids obtained earlier
        Map<Id, Attendee__c> attendeeMap = new Map<Id, Attendee__c>([
            SELECT Name, Email__c 
            FROM Attendee__c 
            WHERE Id IN :attendeeIds]);


        // Loop through each new event attendee record again and add an email for each attendee and their respective event
        for (Event_Attendee__c eventAttendeeNewRecord : EventAttendeeNewRecords) {
    
            // Get the event and attendee objects using the maps created earlier
            Event__c event = eventMap.get(eventAttendeeNewRecord.Event__c);
            Attendee__c attendee = attendeeMap.get(eventAttendeeNewRecord.Attendee__c);
            
            // Create a new email message for the attendee
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new String[]{attendee.Email__c});
            email.setSubject('Pass for the "' + event.Name__c + '"');
            email.setPlainTextBody('Dear ' + attendee.Name + ',\n\nThank you for registering for "' 
                                   + event.Name__c + '" which will be organized on '
                                   + event.Starting_Date__c.format('dd/mm/yyyy') + ' and will be held in '
                                   + event.Location__r.Name + '. We are excited to have you, see you at the event.\n\nThanks,\n'
                                   + event.Event_Organizer__r.Name);
            //Adding email to the list                       
            emails.add(email);
        }
        
        try {
            //Sending the emails to attendees
            Messaging.sendEmail(emails);
        } catch (Exception e) {
            //Calling the method logError to enter any exception into the Error log object
            ErrorLogger.logError(e.getMessage(), 'Error sending email');
        }
    }
}