force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of speakers.</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>This field contains Company of the speaker</description>
    <inlineHelpText>Provide Company of the speaker</inlineHelpText>
    <label>Company</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field contains Email of the Speaker</description>
    <inlineHelpText>Provide Email of the Speaker</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>This field contains Phone of the Speaker</description>
    <inlineHelpText>Provide Phone of the speaker</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SpeakerWebService.cls
/**
 * @description       : This class is a web service for creating Speaker records.
 * @author            : Harshit@mirketa.com
 * @last modified on  : 04-10-2023
 * @last modified by  : Harshit@mirketa.com
**/
@RestResource(urlMapping='/Speakers')
global class SpeakerWebService {
    
    @HttpPost//Post method with parameters of speaker fields.
    global static Id createSpeaker(String name, String email, String phone, String company){
        
        //Creating speaker record
        Speaker__c speaker = new Speaker__c();
        speaker.Name = name;
        speaker.Email__c = email;
        speaker.Phone__c = phone;
        speaker.Company__c = company;

        try{
            //Inserting record and setting status code to 201.
            insert speaker;
            RestContext.response.statusCode = 201;
            return speaker.Id;
        }
        catch(Exception e){

            ErrorLogger.logError(e.getMessage(), 'Speaker web service fail');
            //Xatching error and setting status code to 410.
            RestContext.response.statusCode = 410;
            return null;
        }

    }
}