force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object contains information about the event.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>ticket{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains Lookup relation for Event Organizer of the Event</description>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>This field contains Max Seats  in the Event</description>
    <inlineHelpText>Provide Max Seats in the Event</inlineHelpText>
    <label>Max Seats</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field contains Name of Event</description>
    <inlineHelpText>Provide Name of Event</inlineHelpText>
    <label>Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Starting_Date__c.field-meta.xml
<CustomField>
    <fullName>Starting_Date__c</fullName>
    <description>This field contains Starting Date of Event</description>
    <inlineHelpText>Fill Starting Date of Event</inlineHelpText>
    <label>Starting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <description>This Object include records about Organizers</description>
    <label>Event Organizer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Contains Email of Event Organizer</description>
    <inlineHelpText>Provide Email of Event Organizer</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventWebServiceTest.cls
/**
 * @description       : This class is a test to the web service for fetching event details and event Organiser details.
 * @author            : Harshit@mirketa.com
 * @last modified on  : 04-11-2023
 * @last modified by  : Harshit@mirketa.com
**/
@isTest
public class EventWebServiceTest {

    @isTest
    static void getEventsTest(){

        //Creating Entries for event Organiser and event.(*Did not made records in test setup because we want an empty org for another test method)

        //Event Organiser
        Event_Organizer__c eveOrganiser = new Event_Organizer__c();
        eveOrganiser.Name = 'Harshit kandpal';
        eveOrganiser.Email__c ='Harshitk0011@gmail.com';
        insert eveOrganiser;

        //Event Record
        Event__c event = new Event__c();
        event.Name__C = 'Test Event';
        event.Starting_Date__c = Date.today();
        event.Max_Seats__c = 50;
        event.Event_Organizer__c = eveOrganiser.id;
        insert event;

        Test.startTest();

        RestContext.response = new RestResponse();

        //Calling the method
        EventWebService.getEvents();

        List<Object> results = (List<Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
        map<string, object> ResultDataMap = (map<string, object>) results[0];

        Map<string,Object> eventDataMap = (Map<string,Object>) ResultDataMap.get('event');

        system.assertEquals('Test Event', string.valueOf(eventDataMap.get('name')));

        Test.stopTest();
    }

    @isTest
    static void getNoEventTest(){

        Test.startTest();

        RestContext.response = new RestResponse();
        
        //Calling the method
        EventWebService.getEvents();

        system.assertEquals(null,RestContext.response.responseBody);

        Test.stopTest();
        
    }
}