force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This object contains information about the event.</description>
    <label>Event</label>
    <nameField>
        <displayFormat>ticket{0000}</displayFormat>
        <label>Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{00}</displayFormat>
        <label>Speaker ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events-Speakers</relationshipLabel>
    <relationshipName>Events_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Events-Speakers</relationshipLabel>
    <relationshipName>Events_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <description>This object contains the details of speakers.</description>
    <label>Speaker</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SpeakerRegistartionPageController.cls
/**
 * @description       : This is a controller class for the Speaker Registartion page
 * @author            : Harshit@mirketa.com
 * @last modified on  : 04-04-2023
 * @last modified by  : Harshit@mirketa.com
**/
public with sharing class SpeakerRegistartionPageController {

    // Properties for Event Speaker, Speaker variables and a public eventId to store if is passed through URL
    public Event_Speaker__c eveSpeaker {get; set;}
    public Speaker__c speaker {get; set;}
    public Id eventId;

    // Constructor initializes the properties to new instances of their respective sObjects
    public SpeakerRegistartionPageController() {
        //Get the id from the Apex Page.
        eventId = ApexPages.currentPage().getParameters().get('id');
        eveSpeaker = new Event_Speaker__c();
        speaker = new Speaker__c();

        //If id was passed the assign it to the event variable
        if(eventId != null){
            eveSpeaker.Event__c = eventId;
        }
    }

    // The saveRecord() method inserts the location records, assigns their IDs to the event and organizer, and inserts them as well
    public void saveRecord(){
        Savepoint sp = Database.setSavepoint();

        try{

            insert speaker;

            //Assigning Speaker in Event Speaker object
            eveSpeaker.Speaker__c = speaker.id;
            insert eveSpeaker;
    
            eveSpeaker = new Event_Speaker__c();
            speaker = new Speaker__c();

        }
        catch(Exception e){
             // If an exception occurs, the method logs the error and rolls back the transaction using a savepoint
            ErrorLogger.logError(e.getMessage(),'Error inserting through Visualforce');
            Database.RollBack(sp);
        }
    }
}